const apiUrl = 'https://v4.passwordless.dev';

export const registerToken = async (req, res) => {
    try {
      const page = parseInt(req.body);

      const payload ={
 
        "userId": "user1", // Required. A WebAuthn User Handle, which should be generated by your application. This is used to identify your user (could be a database primary key ID or a guid). Max. 64 bytes. Should not contain PII about the user.
      
        "username": "shawnlaw6669@gmail.com", //Required. A human-palatable identifier for a user account. It is intended only for display, i.e., aiding the user in determining the difference between user accounts with similar displayNames. Used in Browser UI's and never stored on the server
      
        "displayname": "Shawn Law" // A human-palatable name for the account.
      
        //"authenticatorType": "any" //WebAuthn authenticator attachment modality. Can be "any" (default), "platform", which triggers client device-specific options Windows Hello, FaceID, or TouchID, or "cross-platform", which triggers roaming options like security keys.
      
        //"discoverable": true //If true, creates a client-side Discoverable Credential that allows sign in without needing a username.	
      
        //"userVerification": "preferred", //Allows choosing preference for requiring User Verification (biometrics, pin code etc) when authenticating Can be "preferred" (default), "required" or "discouraged".	
      
        //"aliases": ["pjfry@passwordless.dev"], // A array of aliases for the userId, such as an email or username. Used to initiate a sign-in on the client side with the signinWithAlias() method. An alias must be unique to the userId. Defaults to an empty array [].
      
        //"aliasHashing": true // Whether aliases should be hashed before being stored. Defaults to true.
      
      }
        
    } catch (error) {
        console.error('some error:', error);
        return res.status(500).json({ message: 'Server Error' });
    }
}
